### ISSUE TITLE
Typescript Type Library

### ISSUE THREAD

**Issue by marc-lefebvre** [MeasureAuthoringTool/fhir-typescript-models#136]
Can you publish this also as a typescript library?  Currently the model files are not treated as data types.  You would need to add your export classes in some *.d.ts file.

Currently am getting this warning in Visual Studio Code:

Could not find a declaration file for module 'fhir-typescript-models'. '.../node_modules/fhir-typescript-models/dist/src/models/all.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/fhir-typescript-models` if it exists or add a new declaration (.d.ts) file containing `declare module 'fhir-typescript-models';

**Comment by AndrewBird81** [comment]
Hi @marc-lefebvre - thank you for bringing this to our attention. I've fixed this in [this PR](https://github.com/MeasureAuthoringTool/fhir-typescript-models/pull/139) and [released version 1.0.2 to NPM](https://www.npmjs.com/package/fhir-typescript-models). Please let me know if you have any other feedback or issues.
